#########################
#Make File for Assignment #2
#Ian Chang masc0962 
#Jack Aguirre masc0976
#########################

EXEC = a2
FILES = main.cpp opt.cpp lru.cpp clock.cpp
CC =g++
$(EXEC):
	$(CC) -o $(EXEC) main.cpp opt.cpp lru.cpp clock.cpp
	
clean:
	rm $(EXEC)
